services:
  postgres:
    image: postgres:16
    container_name: meu-postgres
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: senhaDesafio
      POSTGRES_DB: financeiro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U desafio -d financeiro"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./src/challenge-backend/
      dockerfile: Dockerfile
    container_name: minha-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=financeiro;Username=desafio;Password=senhaDesafio
      - JwtSettings__Secret=123456wqeq123312edsqa789testesecret67e9tesqwe12dasstesecret
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pgdata: